#include "/Engine/Public/Platform.ush"

Buffer<int> OffScale;
Buffer<float> Input;
RWBuffer<float> Output;

[numthreads(THREADS_X, THREADS_Y, THREADS_Z)]
void FirstCShader(
	uint3 DispatchThreadId : SV_DispatchThreadID,
	uint3 GroupThreadId : SV_GroupThreadID,
	uint3 GroupId : SV_GroupID,
	uint GroupIndex : SV_GroupIndex)
{
	
    Output[GroupThreadId.x] = OffScale[0] + Input[GroupThreadId.x] * OffScale[1];
}